version: 2.1

executors:
    my-executor:
        docker:
            - image: circleci/node:11.0.0
        working_directory: /tmp/bcpa-website

jobs:
    build:
        executor: my-executor

        steps:
            - restore_cache:
                name: Restore source code from cache
                keys:
                    - source-v1-{{ .Branch }}-{{ .Revision }}
                    - source-v1-{{ .Branch }}-
                    - source-v1

            - checkout:
                name: Check out latest source code
                # path: ~/bcpa-website

            - save_cache:
                name: Cache source code
                key: source-v1-{{ .Branch }}-{{ .Revision }}
                paths:
                    - ".git"

            - restore_cache:
                name: Restore backend node_modules from cache
                keys:
                    - npm-backend-v1-{{ .Branch }}-{{ checksum "backend/package.json" }}
                    - npm-backend-v1-{{ .Branch }}-
                    - npm-backend-v1

            - run:
                name: Update npm
                command: sudo npm install -g npm@latest

            - run:
                name: Run npm install
                command: npm install --prefix backend

            - save_cache:
                name: Cache backend node_modules
                key: npm-backend-v1-{{ .Branch }}-{{ checksum "backend/package.json" }}
                paths:
                    - ./backend/node_modules

            - persist_to_workspace:
                root: /tmp/bcpa-website/backend
                paths:
                    - ./*

    test:
        executor: my-executor

        steps:
            - attach_workspace:
                at: /tmp/bcpa-website/backend

            - run:
                name: Run tests
                command: npm test --prefix backend

workflows:
    version: 2.1

    build-and-test:
        jobs:
            - build
            - test:
                requires:
                    - build
      # - run: # run coverage report
      #     name: code-coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      # - store_artifacts: # special step to save test results as as artifact
      #     # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
      #     path: coverage
      #     prefix: coverage
      # - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
      #     path: test-results.xml
      # # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
