version: 2

_defaults: &_defaults
    docker:
        - image: circleci/node:11.0.0
    working_directory: ~/bcpa-website/backend

jobs:
    build:
        <<: *_defaults

        steps:
            - restore_cache:
                name: Restore source code cache
                keys:
                    - source-{{ .Branch }}-{{ .Revision }}
                    - source-{{ .Branch }}-
                    - source-

            - checkout:
                name: Check out latest source code
                path: ~/bcpa-website

            - save_cache:
                name: Save source code cache
                key: source-{{ .Branch }}-{{ .Revision }}
                paths:
                    - ".git"

            - restore_cache:
                name: Restore npm cache
                keys:
                    - npm-{{ .Branch }}-{{ checksum "package.json" }}
                    - npm-{{ .Branch }}-
                    - npm-

            - run:
                name: Update npm
                command: sudo npm install -g npm@latest

            - run:
                name: Run npm install
                command: npm install

            - save_cache:
                name: Save npm cache
                key: npm-{{ .Branch }}-{{ checksum "package.json" }}
                paths:
                    - ./backend/node_modules

    test:
        <<: *_defaults

        steps:
            - run:
                name: Run tests
                command: npm test

      # - run: # run coverage report
      #     name: code-coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      # - store_artifacts: # special step to save test results as as artifact
      #     # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
      #     path: coverage
      #     prefix: coverage
      # - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
      #     path: test-results.xml
      # # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
