version: 2
jobs:
  build:
    working_directory: ~/bcpa-website/frontend
    docker:
      # Configure containers
      - image: circleci/node:11.0.0

    steps:
      # Restore source code cache
      -restore_cache:
        name: Restoring source code cache
        keys:
          - source-{{ .Branch }}-{{ .Revision }}
          - source-{{ .Branch }}-
          - source-

      # Checkout newest source code
      - checkout:
          path: ~/bcpa-website

      # Save source code cache
      - save_cache:
          name: Saving source code cache
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      # Restore npm cache
      - restore_cache:
          name: Restoring npm cache
          keys:
            - npm-{{ .Branch }}-{{ checksum "package.json" }}
            - npm-{{ .Branch }}-
            - npm-

      # Update npm
      - run:
          name: Updating npm
          command: 'sudo npm install -g npm@latest'

      # Run npm install
      - run:
          name: Running npm install
          command: cd frontend && npm install

      # Save npm cache
      - save_cache:
          name: Saving npm cache
          key: npm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./frontend/node_modules

      # Run tests
      - run:
          name: Running tests
          command: cd frontend && npm test

      # - run: # run coverage report
      #     name: code-coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      # - store_artifacts: # special step to save test results as as artifact
      #     # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
      #     path: coverage
      #     prefix: coverage
      # - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
      #     path: test-results.xml
      # # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
